"""
Sandboxed MCP Server — Metabolic Systems Biology
Transport : Streamable HTTP (via FastMCP) — OpenCode connects via type: "remote"
Tool      : execute_sandbox_command
"""

import asyncio
import logging
from datetime import datetime
from pathlib import Path

from mcp.server.fastmcp import FastMCP

# ── Configuration ──────────────────────────────────────────────────────────────
WORKSPACE    = Path("/workspace")
WORKFLOW_LOG = WORKSPACE / "reproducible_workflow.sh"
SESSION_LOG  = WORKSPACE / "agent_session.log"
HOST         = "0.0.0.0"
PORT         = 8080

# ── Logging ────────────────────────────────────────────────────────────────────
WORKSPACE.mkdir(exist_ok=True)
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(SESSION_LOG),
        logging.StreamHandler(),
    ],
)
logger = logging.getLogger(__name__)

# ── Command allowlist ──────────────────────────────────────────────────────────
ALLOWED_PREFIXES = (
    "carve",
    "carveme",
    "memote",
    "python3",
    "python",
    "ls",
    "cat",
    "head",
    "tail",
    "grep",
    "awk",
    "wc",
    "echo",
    "bash /workspace",
)

def is_allowed(cmd: str) -> bool:
    return cmd.strip().startswith(ALLOWED_PREFIXES)

def record_success(command: str) -> None:
    """Append a successful command to the reproducible workflow script."""
    if not WORKFLOW_LOG.exists():
        WORKFLOW_LOG.write_text(
            "#!/bin/bash\n"
            f"# Reproducible workflow — {datetime.now().isoformat()}\n"
            "# Generated by LLM Agent via MCP sandbox\n\n"
        )
    with WORKFLOW_LOG.open("a") as fh:
        fh.write(f"{command}\n")

from mcp.server.transport_security import TransportSecuritySettings

mcp = FastMCP(
    "sysbio-sandbox",
    transport_security=TransportSecuritySettings(
        enable_dns_rebinding_protection=True,
        allowed_hosts=["sandbox:8080", "localhost:8080", "0.0.0.0:8080"],
    ),
)

@mcp.tool()
async def execute_sandbox_command(
    command: str,
    timeout_seconds: int = 1200,
) -> str:
    """Run a shell command inside the secure bioinformatics sandbox.

    Available tools: carve (CarveMe), memote, python3 (COBRApy installed).
    ALL file paths must be absolute and under /workspace/.
    Successful commands (exit 0) are automatically appended to
    /workspace/reproducible_workflow.sh.

    Args:
        command: Shell command to execute.
                 Example: 'carve /workspace/ecoli.fasta -o /workspace/ecoli.xml -v'
        timeout_seconds: Max seconds before the process is killed.
                         Default 1200 for large CarveMe and memote jobs.
    """
    command = command.strip()
    logger.info("TOOL CALL  cmd=%s  timeout=%ds", command, timeout_seconds)

    # ── Allowlist gate ────────────────────────────────────────────────────────
    if not is_allowed(command):
        msg = (
            f"BLOCKED: '{command[:100]}' is not permitted.\n"
            f"Allowed prefixes: {ALLOWED_PREFIXES}"
        )
        logger.warning("BLOCKED    cmd=%s", command)
        return msg

    # ── Execute asynchronously ────────────────────────────────────────────────
    try:
        proc = await asyncio.create_subprocess_shell(
            command,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            cwd="/workspace",
        )
        
        stdout_chunks = []
        stderr_chunks = []

        import sys

        async def read_stream(stream, chunks, is_stderr=False):
            while True:
                line = await stream.readline()
                if not line:
                    break
                decoded = line.decode("utf-8", errors="replace")
                chunks.append(decoded)
                
                # Stream directly to process streams and flush to guarantee Docker sees it immediately
                if is_stderr:
                    sys.stderr.write(f"  [STDERR] {decoded}")
                    sys.stderr.flush()
                else:
                    sys.stdout.write(f"  [STDOUT] {decoded}")
                    sys.stdout.flush()

        # Read both streams concurrently while awaiting the process
        await asyncio.wait_for(
            asyncio.gather(
                read_stream(proc.stdout, stdout_chunks, is_stderr=False),
                read_stream(proc.stderr, stderr_chunks, is_stderr=True),
                proc.wait()
            ),
            timeout=timeout_seconds
        )
        
        stdout = "".join(stdout_chunks)
        stderr = "".join(stderr_chunks)
        returncode = proc.returncode
    except asyncio.TimeoutError:
        # Kill the process if it's still running
        try:
            proc.kill()
            await proc.wait()
        except Exception:
            pass
        msg = f"TIMEOUT: process exceeded {timeout_seconds}s.\nCommand: {command}"
        logger.error("TIMEOUT    cmd=%s", command)
        return msg
    except Exception as exc:
        msg = f"EXECUTION ERROR: {type(exc).__name__}: {exc}"
        logger.error("ERROR      %s", msg)
        return msg

    # ── Code trail: log only successes ────────────────────────────────────────
    # Memote returns 1 when validation tests fail, which is expected behavior
    # for a draft model, so we treat it as a success for logging purposes.
    is_success = returncode == 0 or (command.startswith("memote") and returncode == 1)
    
    if is_success:
        record_success(command)
        logger.info("SUCCESS    exit=%d  cmd=%s", returncode, command)
    else:
        logger.warning("FAILED     exit=%d  cmd=%s", returncode, command)

    return (
        f"EXIT CODE: {returncode}\n"
        f"STDOUT:\n{stdout or '(empty)'}\n"
        f"STDERR:\n{stderr or '(empty)'}"
    )

import os

# ── Entry point ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    # Override FastMCP default host/port
    mcp.settings.host = HOST
    mcp.settings.port = PORT
    logger.info("MCP sandbox starting  http://%s:%d", HOST, PORT)
    logger.info("MCP endpoint  →  http://%s:%d/mcp", HOST, PORT)
    mcp.run(transport="streamable-http")
